version: '3.7'

services:
  coupon:
    build: services/coupon-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - TZ=Asia/Seoul
    depends_on:
      - mongodb
      - kafka

  order:
    build: services/order-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - TZ=Asia/Seoul
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started

  order-1:
    build: services/order-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - TZ=Asia/Seoul
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started

  mall-composite:
    build: services/mall-composite
    mem_limit: 350m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - TZ=Asia/Seoul
    depends_on:
      kafka:
        condition: service_started


  # DB
  mongodb:
    image: mongo:4.4.2
    mem_limit: 350m
    ports:
      - "27017:27017"
    command: mongod

  mysql:
    image: mysql:8.0.22
    mem_limit: 350m
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=hanwool
      - MYSQL_DATABASE=order
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=hanwool
      - TZ=Asia/Seoul
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-uuser", "-ppwd", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10

  kafka:
    image: wurstmeister/kafka:2.12-2.2.0
    mem_limit: 350m
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "orders:2:1,coupons:1:1:delete"
      TZ: Asia/Seoul
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    mem_limit: 350m
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper