version: '3.7'

services:
  coupon:
    build: services/coupon-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - mongodb

  order:
    build: services/order-service
    mem_limit: 350m
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      mysql:
        condition: service_healthy

  mall-composite:
    build: services/mall-composite
    mem_limit: 350m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev


  # DB
  mongodb:
    image: mongo:4.4.2
    mem_limit: 350m
    ports:
      - "27017:27017"
    command: mongod

  mysql:
    image: mysql:8.0.22
    mem_limit: 350m
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=hanwool
      - MYSQL_DATABASE=order
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=hanwool
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-uuser", "-ppwd", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10