apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: msa-e-commerce
build:
  artifacts:
  - image: mall-composite
    context: services\mall-composite
    docker: {}
  - image: order
    context: services\order-service
    docker: {}
deploy:
  kubectl:
    manifests:
    - kubernetes-manifests/mall-composite.yaml
    - kubernetes-manifests/order-service.yaml
    - kubernetes-manifests/order-secret.yaml
    - kubernetes-manifests/order-configmap.yaml
#    - kubernetes-manifests/composite-ingress.yaml

