logging:
    level:
        root: INFO
        me.hanwool: DEBUG
        org.apache:
            kafka: WARN
            kafka.clients: WARN
        org.springframework:
            kafka:
                requestreply: DEBUG

server:
    port: 7000
    error:
        include-message: always
    servlet:
        context-path: /

app:
    coupon-service:
        host: localhost
        port: 7001
    order-service:
        host: localhost
        port: 7002

spring:
    kafka:
        template:
            default-topic: composite
        consumer:
            group-id: compsiteGroup
        bootstrap-servers: localhost:9092
        client-id: 1

## custom
kafka.output.orders.topic: orders
kafka.input.topic: composite
kafka.consumer.group.id: compsiteGroup

---
spring:
    profiles: dev
    kafka:
        bootstrap-servers: kafka:9092
logging:
    level:
        root: INFO
        me.hanwool: DEBUG

server:
    port: 8080
    error:
        include-message: always

app:
    coupon-service:
        host: coupon
        port: 8080
    order-service:
        host: order
        port: 8080

---
spring:
    profiles: stage
    kafka:
        bootstrap-servers: hw-chart-kafka-0.hw-chart-kafka-headless.default.svc.cluster.local:9092

app:
    coupon-service:
        host: coupon
        port: 8080
    order-service:
        host: order
        port: 8087

server:
    port: 8088

---
spring:
    profiles: prod

logging:
    level:
        root: INFO
        me.hanwool: INFO

server:
    port: 8080
    error:
        include-message: never

