spring.data.mongodb:
  host: localhost
  port: 27017
  database: coupon

logging:
  level:
    root: INFO
    me.hanwool: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

server:
  port: 7001
  error:
    include-message: always

---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: INFO
    me.hanwool: INFO

server:
  port: 8080
  error:
    include-message: always

---
spring:
  config:
    activate:
      on-profile: stage

logging:
  level:
    root: INFO
    me.hanwool: INFO

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    root: INFO
    me.hanwool: INFO

server:
  port: 8080
  error:
    include-message: never