spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: coupondb

logging:
  level:
    root: INFO
    me.hanwool: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

server:
  port: 7001
  error:
    include-message: always

---
spring:
  profiles: dev

  data:
    mongodb:
      host: mongodb
      port: 27017
      database: coupondb

logging:
  level:
    root: INFO
    me.hanwool: INFO

server:
  port: 8080
  error:
    include-message: always

---
spring:
  profiles: stage

server:
  port: 8080

---
spring:
  profiles: prod

logging:
  level:
    root: INFO
    me.hanwool: INFO

server:
  port: 8080
  error:
    include-message: never