apiVersion: v1
kind: Service
metadata:
  name: order
spec:
  selector:
    app: order
  ports:
    - port: 8087
      targetPort: 8077
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: order
          ports:
            - containerPort: 8077
          resources:
            limits:
              memory: 350Mi
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: stage
            - name: TZ
              value: Asia/Seoul
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: order-configmap
                  key: db_host
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: order-configmap
                  key: db_name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: order-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hw-chart-mysql
                  key: mysql-password
