apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: order-space
spec:
  selector:
    app: order
  ports:
    - port: 8087
      targetPort: 8077
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  namespace: order-space
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: order
          ports:
            - containerPort: 8077
          resources:
            limits:
              memory: 350Mi
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: stage
            - name: TZ
              value: Asia/Seoul
            - name: DB_HOST   # Setting Database host address from configMap
#              value: mysql.order-space.svc.cluster.local:3306
              valueFrom:
                configMapKeyRef:
                  name: order-configmap  # name of configMap
                  key: db_host
            - name: DB_NAME  # Setting Database name from configMap
#              value: orders
              valueFrom:
                configMapKeyRef:
                  name: order-configmap
                  key: db_name
            - name: DB_USERNAME  # Setting Database username from Secret
#              value: order_admin
              valueFrom:
                secretKeyRef:
                  name: order-secret # Secret Name
                  key: username
            - name: DB_PASSWORD # Setting Database password from Secret
#              value: hanwool
              valueFrom:
                secretKeyRef:
                  name: order-secret
                  key: password
