apiVersion: v1
kind: Secret
metadata:
  name: order-secret-sql
  namespace: order-space
type: Opaque
stringData:
  initdb.sql : |
    CREATE USER 'order_admin'@'%' IDENTIFIED BY 'hanwool';
    GRANT ALL PRIVILEGES ON orders.* TO order_admin@'%';