logging:
  level:
    root: INFO
    me.hanwool: DEBUG

server:
  port: 7002
  error:
    include-message: always

---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: INFO
    me.hanwool: DEBUG

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: stage

logging:
  level:
    root: INFO
    me.hanwool: INFO

server:
  port: 8080
  error:
    include-message: never

---
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    root: INFO
    me.hanwool: INFO

server:
  port: 8080