spring:
  datasource:
    url: jdbc:mysql://localhost/orders?characterEncoding=UTF-8&serverTimezone=UTC&autoReconnection=true
    username: root
    password: hanwool
  hikari:
    initializationFailTimeout: 60000
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
    hibernate:
      ddl-auto: update
  kafka:
    template:
      default-topic: orders
    consumer:
      group-id: orderGroup
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: me.hanwool.mallutilapp.*
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    bootstrap-servers: localhost:9092

logging:
  level:
    root: INFO
    me.hanwool: DEBUG
    org.apache.kafka: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  port: 7002
  error:
    include-message: always

## custom
kafka.output.composite.topic: composite
kafka.input.topic: orders
kafka.consumer.group.id: orderGroup

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://mysql/orders?characterEncoding=UTF-8&serverTimezone=UTC&autoReconnection=true
    username: root
    password: hanwool
  hikari:
    initializationFailTimeout: 60000
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
  kafka:
    bootstrap-servers: kafka:9092

server:
  port: 8080

---
spring:
  profiles: stage
  datasource:
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  kafka:
    bootstrap-servers: hw-chart-kafka-0.hw-chart-kafka-headless.default.svc.cluster.local:9092

server:
  port: 8077

---
spring:
  profiles: prod

  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: INFO
    me.hanwool: INFO

server:
  port: 8087
  error:
    include-message: never